# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingApp', '0005_auto_20171119_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.PositiveIntegerField(default=54291, unique=True),
        ),
    ]
