# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingApp', '0002_auto_20171118_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.PositiveIntegerField(default=48441),
        ),
    ]
