# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingApp', '0003_auto_20171118_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='receiver',
            new_name='receiver_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='title',
        ),
        migrations.AddField(
            model_name='transfer',
            name='receiver_name',
            field=models.TextField(default='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.PositiveIntegerField(default=3044, unique=True),
        ),
    ]
