# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingApp', '0007_auto_20180104_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.PositiveIntegerField(default=92667, unique=True),
        ),
    ]
